[features]
seeds = false
skip-lint = false

[programs.localnet]
mycalculatordapp = "FEZtVUk1M5NQQaJidJauwtJb4xdyDUpNxA1ckX3Dkjy4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/diptendudas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
